---
name: module3_task1
on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: |
            cd module3_task1
            make help

      - name: Setup Hugo
        run: |
            cd module3_task1
            ./setup.sh

      - name: build
        run: |
            cd module3_task1
            make build

      - name: test
        run: |
          cd module3_task1
          make test

      - name: run
        run: |
          cd module3_task1
          make run

      - name: clean
        run: |
          cd module3_task1
          make clean
