---
name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: |
            cd module3_task1
            make help
      
      - name: Setup Hugo
        run:
            ./setup.sh

      - name: build
        run:
            make build
      
      - name: test
        run:
            make test
      
      - name: run
        run:
            make run
      
      - name: clean
        run:
            make clean
