---
name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: module3_task0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: |
            cd module3_task1
            make help

