---
name: module4_task1
on:
  push:
    branches:
      - master
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
            docker --version
            
      - name: Build Docker Image
        run: |
            cd module4_task1
            make build-docker
            
      - name: Validate Makefile
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make help

      - name: Setup Hugo
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make setup

      - name: Build
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make build

      - name: Test
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make test

      - name: Run unit-tests
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make unit-tests

      - name: Run integration-tests
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make integration-tests

      - name: Run
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make run

      - name: Package
        run: |
            cd module4_task1
            docker run --rm -v ${{ github.workspace }}:/app -w /app awesome:build make package

      - name: Read release notes
        id: DEPLOY
        run: |
          echo "::set-output name=body::$(cat module3_task5/DEPLOY.md)"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.1
          files: module3_task5/awesome-website.zip
          body: ${{ steps.DEPLOY.outputs.body }}
          token: ${{ secrets.RELEASETOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: lint
        run: |
          cd module3_task5
          make lint

      - name: Deploy Preview to Netlify
        if: github.event_name == 'pull_request'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module3_task5/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "#${{ github.event.pull_request.number }}"
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module3_task5/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy production from GitHub Actions"
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: clean
        run: |
          cd module3_task5
